In [10]:
pip install influxdb

WARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: influxdb in /opt/conda/lib/python3.7/site-packages (5.3.0)
Requirement already satisfied: requests>=2.17.0 in /opt/conda/lib/python3.7/site-packages (from influxdb) (2.23.0)
Requirement already satisfied: msgpack==0.6.1 in /opt/conda/lib/python3.7/site-packages (from influxdb) (0.6.1)
Requirement already satisfied: python-dateutil>=2.6.0 in /opt/conda/lib/python3.7/site-packages (from influxdb) (2.8.1)
Requirement already satisfied: pytz in /opt/conda/lib/python3.7/site-packages (from influxdb) (2020.1)
Requirement already satisfied: six>=1.10.0 in /opt/conda/lib/python3.7/site-packages (from influxdb) (1.14.0)
Requirement already satisfied: idna<3,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests>=2.17.0->influxdb) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests>=2.17.0->influxdb) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests>=2.17.0->influxdb) (2020.4.5.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /opt/conda/lib/python3.7/site-packages (from requests>=2.17.0->influxdb) (3.0.4)
Note: you may need to restart the kernel to use updated packages.

In [11]:
import pandas as pd
from influxdb import DataFrameClient

In [39]:
import json
from pandas.io.json import json_normalize

In [13]:
user = 'root'
password = 'root'
host='influxdb' #172.28.1.2 #localhost #3.14.5.146 - kozos osztaly InfluxDB szerver
port=8086
dbname='base' #az en adatbazis nevem
protocol = 'line' #json
client = DataFrameClient(host, port, user, password, dbname)

In [14]:
client.query('show databases')

ResultSet({'('databases', None)': [{'name': '_internal'}, {'name': 'base'}]})

In [225]:
uj = pd.read_csv('alma.csv', encoding='utf-8')

In [226]:
uj

,Unnamed: 0,_county_code,_total_county,_total_healed,_total_dead,_county,date,lat,long
0,0,AB,309,22,17,Alba,2020-05-18,46.066667,23.583333
1,1,AR,589,1,74,Arad,2020-05-18,46.183333,21.316667
2,2,AG,259,0,20,Argeş,2020-05-18,44.850000,24.866667
3,3,BC,430,0,49,Bacău,2020-05-18,46.566667,26.900000
4,4,BH,504,0,19,Bihor,2020-05-18,47.066667,21.933333
5,5,BN,290,0,24,Bistriţa-Năsăud,2020-05-18,47.133333,24.483333
6,6,BT,634,0,42,Botoşani,2020-05-18,47.750000,26.666667
7,7,BV,555,0,41,Braşov,2020-05-18,45.633333,25.583333
8,8,BR,20,0,0,Brăila,2020-05-18,45.266667,27.983333
9,9,B,1332,3,74,Bucureşti,2020-05-18,44.433333,26.100000
10,10,BZ,119,0,0,Buzău,2020-05-18,45.150000,26.833333
11,11,CS,103,4,6,Caraş-Severin,2020-05-18,45.300833,21.889167
12,12,CJ,455,1,15,Cluj,2020-05-18,46.766667,23.600000
13,13,CT,210,2,15,Constanţa,2020-05-18,44.183333,28.650000
14,14,CV,214,0,9,Covasna,2020-05-18,45.866667,25.783333
15,15,CL,70,0,3,Călăraşi,2020-05-18,44.200000,27.333333
16,16,DJ,150,0,3,Dolj,2020-05-18,44.316667,23.800000
17,17,DB,254,6,10,Dâmboviţa,2020-05-18,44.933333,25.450000
18,18,GL,494,0,81,Galaţi,2020-05-18,45.450000,28.050000
19,19,GR,187,0,4,Giurgiu,2020-05-18,43.883333,25.966667
20,20,GJ,99,1,7,Gorj,2020-05-18,45.050000,23.283333
21,21,HR,68,0,0,Harghita,2020-05-18,46.350000,25.800000
22,22,HD,595,3,68,Hunedoara,2020-05-18,45.883333,22.900000
23,23,IL,316,0,20,Ialomiţa,2020-05-18,44.566667,27.366667
24,24,IS,386,1,26,Iaşi,2020-05-18,47.166667,27.600000
25,27,MM,68,1,3,Maramureş,2020-05-18,47.666667,23.583333
26,28,MH,94,0,12,Mehedinţi,2020-05-18,44.631944,22.656111
27,29,MS,632,0,61,Mureş,2020-05-18,46.550000,24.566667
28,30,NT,787,0,44,Neamţ,2020-05-18,46.916667,26.333333
29,31,OT,54,1,2,Olt,2020-05-18,44.433333,24.316667
30,32,PH,74,0,7,Prahova,2020-05-18,44.950000,26.016667
31,33,SM,56,0,8,Satu Mare,2020-05-18,47.800000,22.883333
32,34,SB,437,0,37,Sibiu,2020-05-18,45.800000,24.150000
33,35,SV,3134,4,189,Suceava,2020-05-18,47.650000,26.233333
34,36,SJ,76,0,10,Sălaj,2020-05-18,47.200000,23.050000
35,37,TR,115,0,8,Teleorman,2020-05-18,43.983333,25.333333
36,38,TM,485,4,49,Timiş,2020-05-18,45.749444,21.227222
37,39,TL,110,0,1,Tulcea,2020-05-18,45.166667,28.800000
38,40,VS,154,0,17,Vaslui,2020-05-18,46.633333,27.733333
39,41,VN,510,0,31,Vrancea,2020-05-18,45.700000,27.183333
40,42,VL,31,0,2,Vâlcea,2020-05-18,45.100000,24.366667

In [227]:
df=pd.DataFrame(uj).set_index('date')
df.index=pd.to_datetime(df.index)

In [228]:
df

,Unnamed: 0,_county_code,_total_county,_total_healed,_total_dead,_county,lat,long
date,,,,,,,,
2020-05-18,0,AB,309,22,17,Alba,46.066667,23.583333
2020-05-18,1,AR,589,1,74,Arad,46.183333,21.316667
2020-05-18,2,AG,259,0,20,Argeş,44.850000,24.866667
2020-05-18,3,BC,430,0,49,Bacău,46.566667,26.900000
2020-05-18,4,BH,504,0,19,Bihor,47.066667,21.933333
2020-05-18,5,BN,290,0,24,Bistriţa-Năsăud,47.133333,24.483333
2020-05-18,6,BT,634,0,42,Botoşani,47.750000,26.666667
2020-05-18,7,BV,555,0,41,Braşov,45.633333,25.583333
2020-05-18,8,BR,20,0,0,Brăila,45.266667,27.983333
2020-05-18,9,B,1332,3,74,Bucureşti,44.433333,26.100000
2020-05-18,10,BZ,119,0,0,Buzău,45.150000,26.833333
2020-05-18,11,CS,103,4,6,Caraş-Severin,45.300833,21.889167
2020-05-18,12,CJ,455,1,15,Cluj,46.766667,23.600000
2020-05-18,13,CT,210,2,15,Constanţa,44.183333,28.650000
2020-05-18,14,CV,214,0,9,Covasna,45.866667,25.783333
2020-05-18,15,CL,70,0,3,Călăraşi,44.200000,27.333333
2020-05-18,16,DJ,150,0,3,Dolj,44.316667,23.800000
2020-05-18,17,DB,254,6,10,Dâmboviţa,44.933333,25.450000
2020-05-18,18,GL,494,0,81,Galaţi,45.450000,28.050000
2020-05-18,19,GR,187,0,4,Giurgiu,43.883333,25.966667
2020-05-18,20,GJ,99,1,7,Gorj,45.050000,23.283333
2020-05-18,21,HR,68,0,0,Harghita,46.350000,25.800000
2020-05-18,22,HD,595,3,68,Hunedoara,45.883333,22.900000
2020-05-18,23,IL,316,0,20,Ialomiţa,44.566667,27.366667
2020-05-18,24,IS,386,1,26,Iaşi,47.166667,27.600000
2020-05-18,27,MM,68,1,3,Maramureş,47.666667,23.583333
2020-05-18,28,MH,94,0,12,Mehedinţi,44.631944,22.656111
2020-05-18,29,MS,632,0,61,Mureş,46.550000,24.566667
2020-05-18,30,NT,787,0,44,Neamţ,46.916667,26.333333
2020-05-18,31,OT,54,1,2,Olt,44.433333,24.316667
2020-05-18,32,PH,74,0,7,Prahova,44.950000,26.016667
2020-05-18,33,SM,56,0,8,Satu Mare,47.800000,22.883333
2020-05-18,34,SB,437,0,37,Sibiu,45.800000,24.150000
2020-05-18,35,SV,3134,4,189,Suceava,47.650000,26.233333
2020-05-18,36,SJ,76,0,10,Sălaj,47.200000,23.050000
2020-05-18,37,TR,115,0,8,Teleorman,43.983333,25.333333
2020-05-18,38,TM,485,4,49,Timiş,45.749444,21.227222
2020-05-18,39,TL,110,0,1,Tulcea,45.166667,28.800000
2020-05-18,40,VS,154,0,17,Vaslui,46.633333,27.733333
2020-05-18,41,VN,510,0,31,Vrancea,45.700000,27.183333
2020-05-18,42,VL,31,0,2,Vâlcea,45.100000,24.366667

In [27]:

df['countyInfectionsNumbers']=df['countyInfectionsNumbers'].astype(int)
df['population']=df['population'].astype(int)
client.write_points(df, 'rom2', protocol=protocol,
                        field_columns=['countyInfectionsNumbers', 'population'],
                        tag_columns=['jud', 'lat', 'long'])

True

In [150]:
data

{'data': {'total': 17036,
  'data': [{'county_code': 'SV',
    'total_county': 3134,
    'total_healed': 4,
    'total_dead': 189,
    'county': 'SUCEAVA'},
   {'county_code': 'B',
    'total_county': 1332,
    'total_healed': 3,
    'total_dead': 74,
    'county': 'BUCUREÈ\x98TI'},
   {'county_code': 'NA',
    'total_county': 1182,
    'total_healed': 0,
    'total_dead': 0,
    'county': 'JUDEÈ\x9a NECUNOSCUT'},
   {'county_code': 'NT',
    'total_county': 787,
    'total_healed': 0,
    'total_dead': 44,
    'county': 'NEAMÈ\x9a'},
   {'county_code': 'BT',
    'total_county': 634,
    'total_healed': 0,
    'total_dead': 42,
    'county': 'BOTOÈ\x98ANI'},
   {'county_code': 'MS',
    'total_county': 632,
    'total_healed': 0,
    'total_dead': 61,
    'county': 'MUREÈ\x98'},
   {'county_code': 'HD',
    'total_county': 595,
    'total_healed': 3,
    'total_dead': 68,
    'county': 'HUNEDOARA'},
   {'county_code': 'AR',
    'total_county': 589,
    'total_healed': 1,
    'total_dead': 74,
    'county': 'ARAD'},
   {'county_code': 'BV',
    'total_county': 555,
    'total_healed': 0,
    'total_dead': 41,
    'county': 'BRAÈ\x98OV'},
   {'county_code': 'VN',
    'total_county': 510,
    'total_healed': 0,
    'total_dead': 31,
    'county': 'VRANCEA'},
   {'county_code': 'BH',
    'total_county': 504,
    'total_healed': 0,
    'total_dead': 19,
    'county': 'BIHOR'},
   {'county_code': 'GL',
    'total_county': 494,
    'total_healed': 0,
    'total_dead': 81,
    'county': 'GALAÈ\x9aI'},
   {'county_code': 'TM',
    'total_county': 485,
    'total_healed': 4,
    'total_dead': 49,
    'county': 'TIMIÈ\x98'},
   {'county_code': 'CJ',
    'total_county': 455,
    'total_healed': 1,
    'total_dead': 15,
    'county': 'CLUJ'},
   {'county_code': 'SB',
    'total_county': 437,
    'total_healed': 0,
    'total_dead': 37,
    'county': 'SIBIU'},
   {'county_code': 'BC',
    'total_county': 430,
    'total_healed': 0,
    'total_dead': 49,
    'county': 'BACÄ\x82U'},
   {'county_code': 'IF',
    'total_county': 395,
    'total_healed': 0,
    'total_dead': 13,
    'county': 'ILFOV'},
   {'county_code': 'IS',
    'total_county': 386,
    'total_healed': 1,
    'total_dead': 26,
    'county': 'IAÈ\x98I'},
   {'county_code': 'IL',
    'total_county': 316,
    'total_healed': 0,
    'total_dead': 20,
    'county': 'IALOMIÈ\x9aA'},
   {'county_code': 'AB',
    'total_county': 309,
    'total_healed': 22,
    'total_dead': 17,
    'county': 'ALBA'},
   {'county_code': 'BN',
    'total_county': 290,
    'total_healed': 0,
    'total_dead': 24,
    'county': 'BISTRIÈ\x9aA-NÄ\x82SÄ\x82UD'},
   {'county_code': 'AG',
    'total_county': 259,
    'total_healed': 0,
    'total_dead': 20,
    'county': 'ARGEÈ\x98'},
   {'county_code': 'DB',
    'total_county': 254,
    'total_healed': 6,
    'total_dead': 10,
    'county': 'DÃ\x82MBOVIÈ\x9aA'},
   {'county_code': 'CV',
    'total_county': 214,
    'total_healed': 0,
    'total_dead': 9,
    'county': 'COVASNA'},
   {'county_code': 'CT',
    'total_county': 210,
    'total_healed': 2,
    'total_dead': 15,
    'county': 'CONSTANÈ\x9aA'},
   {'county_code': 'GR',
    'total_county': 187,
    'total_healed': 0,
    'total_dead': 4,
    'county': 'GIURGIU'},
   {'county_code': 'VS',
    'total_county': 154,
    'total_healed': 0,
    'total_dead': 17,
    'county': 'VASLUI'},
   {'county_code': 'DJ',
    'total_county': 150,
    'total_healed': 0,
    'total_dead': 3,
    'county': 'DOLJ'},
   {'county_code': 'BZ',
    'total_county': 119,
    'total_healed': 0,
    'total_dead': 0,
    'county': 'BUZÄ\x82U'},
   {'county_code': 'TR',
    'total_county': 115,
    'total_healed': 0,
    'total_dead': 8,
    'county': 'TELEORMAN'},
   {'county_code': 'TL',
    'total_county': 110,
    'total_healed': 0,
    'total_dead': 1,
    'county': 'TULCEA'},
   {'county_code': 'CS',
    'total_county': 103,
    'total_healed': 4,
    'total_dead': 6,
    'county': 'CARAÈ\x98-SEVERIN'},
   {'county_code': 'GJ',
    'total_county': 99,
    'total_healed': 1,
    'total_dead': 7,
    'county': 'GORJ'},
   {'county_code': 'MH',
    'total_county': 94,
    'total_healed': 0,
    'total_dead': 12,
    'county': 'MEHEDINÈ\x9aI'},
   {'county_code': 'SJ',
    'total_county': 76,
    'total_healed': 0,
    'total_dead': 10,
    'county': 'SÄ\x82LAJ'},
   {'county_code': 'PH',
    'total_county': 74,
    'total_healed': 0,
    'total_dead': 7,
    'county': 'PRAHOVA'},
   {'county_code': 'CL',
    'total_county': 70,
    'total_healed': 0,
    'total_dead': 3,
    'county': 'CÄ\x82LÄ\x82RAÈ\x98I'},
   {'county_code': 'HR',
    'total_county': 68,
    'total_healed': 0,
    'total_dead': 0,
    'county': 'HARGHITA'},
   {'county_code': 'MM',
    'total_county': 68,
    'total_healed': 1,
    'total_dead': 3,
    'county': 'MARAMUREÈ\x98'},
   {'county_code': 'SM',
    'total_county': 56,
    'total_healed': 0,
    'total_dead': 8,
    'county': 'SATU MARE'},
   {'county_code': 'OT',
    'total_county': 54,
    'total_healed': 1,
    'total_dead': 2,
    'county': 'OLT'},
   {'county_code': 'VL',
    'total_county': 31,
    'total_healed': 0,
    'total_dead': 2,
    'county': 'VÃ\x82LCEA'},
   {'county_code': 'BR',
    'total_county': 20,
    'total_healed': 0,
    'total_dead': 0,
    'county': 'BRÄ\x82ILA'}]}}

In [ ]:
   elet = pd.DataFrame(obj['currentDayStats'], columns=['distributionByAge'])

In [ ]:
elet

In [ ]:
hist = pd.DataFrame(obj['historicalData']['2020-05-17'], columns=['distributionByAge'])

In [28]:
adat = {'date':  ['2020-05-18'],
        'karanten': [12351],
        'elszigetels': [17797],
        'halalozasok': [1107],
        }

In [31]:
korte = pd.DataFrame (adat, columns = ['date','karanten','elszigetels','halalozasok'])

In [212]:
df=pd.DataFrame(valamijo).set_index('date')
df.index=pd.to_datetime(df.index)

In [230]:
df['_total_county']=df['_total_county'].astype(int)
df['_total_healed']=df['_total_healed'].astype(int)
df['_total_dead']=df['_total_dead'].astype(int)
client.write_points(df, 'romVegsoVeg', protocol=protocol,
                        field_columns=['_total_county', '_total_healed', '_total_dead'],
                        tag_columns=['_county', 'lat', 'long', '_county_code', '_total_county', '_total_healed', '_total_dead'])

True

In [231]:
megyek = df['_county'].tolist()

In [232]:
megyek

['Alba',
 'Arad',
 'Argeş',
 'Bacău',
 'Bihor',
 'Bistriţa-Năsăud',
 'Botoşani',
 'Braşov',
 'Brăila',
 'Bucureşti',
 'Buzău',
 'Caraş-Severin',
 'Cluj',
 'Constanţa',
 'Covasna',
 'Călăraşi',
 'Dolj',
 'Dâmboviţa',
 'Galaţi',
 'Giurgiu',
 'Gorj',
 'Harghita',
 'Hunedoara',
 'Ialomiţa',
 'Iaşi',
 'Maramureş',
 'Mehedinţi',
 'Mureş',
 'Neamţ',
 'Olt',
 'Prahova',
 'Satu Mare',
 'Sibiu',
 'Suceava',
 'Sălaj',
 'Teleorman',
 'Timiş',
 'Tulcea',
 'Vaslui',
 'Vrancea',
 'Vâlcea']

In [47]:
df=pd.read_json (r'getCasesByCounty.json', encoding='latin-1')

In [54]:
from pandas.io.json import json_normalize
json_normalize(data)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

   data.total                                          data.data
0       17036  [{'county_code': 'SV', 'total_county': 3134, '...

In [45]:
df.keys()

Index(['data'], dtype='object')

In [49]:
data = json.loads('getCasesByCounty.json', encoding='latin-1')

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [57]:
with open('getCasesByCounty.json', encoding='latin-1') as json_file:

In [61]:
adatok = pd.DataFrame.from_dict(data, orient='index')

In [62]:
adatok

      total                                               data
data  17036  [{'county_code': 'SV', 'total_county': 3134, '...

In [127]:
with open('getCasesByCounty.json', 'r') as j:
     contents = json.loads(j.read())

In [117]:
jsonframe=pd.json_normalize(contents, max_level=4)

In [134]:
result = pd.json_normalize(contents, 'data',['total_county', 'total_healed', 'total_dead', 'county'], errors='ignore')

ValueError: Conflicting metadata name total_county, need distinguishing prefix

In [140]:
valamijo = pd.DataFrame.from_dict(
                  pd.json_normalize(contents,
                                 'data',
                                 ['total_county', 'total_healed', 'total_dead', 'county'], errors='ignore', record_prefix='_'
                                ), orient='columns')

In [204]:
valamijo=valamijo.drop(25)

In [222]:
valamijo.to_csv('alma.csv')

In [233]:
uj

,Unnamed: 0,_county_code,_total_county,_total_healed,_total_dead,_county,date,lat,long
0,0,AB,309,22,17,Alba,2020-05-18,46.066667,23.583333
1,1,AR,589,1,74,Arad,2020-05-18,46.183333,21.316667
2,2,AG,259,0,20,Argeş,2020-05-18,44.850000,24.866667
3,3,BC,430,0,49,Bacău,2020-05-18,46.566667,26.900000
4,4,BH,504,0,19,Bihor,2020-05-18,47.066667,21.933333
5,5,BN,290,0,24,Bistriţa-Năsăud,2020-05-18,47.133333,24.483333
6,6,BT,634,0,42,Botoşani,2020-05-18,47.750000,26.666667
7,7,BV,555,0,41,Braşov,2020-05-18,45.633333,25.583333
8,8,BR,20,0,0,Brăila,2020-05-18,45.266667,27.983333
9,9,B,1332,3,74,Bucureşti,2020-05-18,44.433333,26.100000
10,10,BZ,119,0,0,Buzău,2020-05-18,45.150000,26.833333
11,11,CS,103,4,6,Caraş-Severin,2020-05-18,45.300833,21.889167
12,12,CJ,455,1,15,Cluj,2020-05-18,46.766667,23.600000
13,13,CT,210,2,15,Constanţa,2020-05-18,44.183333,28.650000
14,14,CV,214,0,9,Covasna,2020-05-18,45.866667,25.783333
15,15,CL,70,0,3,Călăraşi,2020-05-18,44.200000,27.333333
16,16,DJ,150,0,3,Dolj,2020-05-18,44.316667,23.800000
17,17,DB,254,6,10,Dâmboviţa,2020-05-18,44.933333,25.450000
18,18,GL,494,0,81,Galaţi,2020-05-18,45.450000,28.050000
19,19,GR,187,0,4,Giurgiu,2020-05-18,43.883333,25.966667
20,20,GJ,99,1,7,Gorj,2020-05-18,45.050000,23.283333
21,21,HR,68,0,0,Harghita,2020-05-18,46.350000,25.800000
22,22,HD,595,3,68,Hunedoara,2020-05-18,45.883333,22.900000
23,23,IL,316,0,20,Ialomiţa,2020-05-18,44.566667,27.366667
24,24,IS,386,1,26,Iaşi,2020-05-18,47.166667,27.600000
25,27,MM,68,1,3,Maramureş,2020-05-18,47.666667,23.583333
26,28,MH,94,0,12,Mehedinţi,2020-05-18,44.631944,22.656111
27,29,MS,632,0,61,Mureş,2020-05-18,46.550000,24.566667
28,30,NT,787,0,44,Neamţ,2020-05-18,46.916667,26.333333
29,31,OT,54,1,2,Olt,2020-05-18,44.433333,24.316667
30,32,PH,74,0,7,Prahova,2020-05-18,44.950000,26.016667
31,33,SM,56,0,8,Satu Mare,2020-05-18,47.800000,22.883333
32,34,SB,437,0,37,Sibiu,2020-05-18,45.800000,24.150000
33,35,SV,3134,4,189,Suceava,2020-05-18,47.650000,26.233333
34,36,SJ,76,0,10,Sălaj,2020-05-18,47.200000,23.050000
35,37,TR,115,0,8,Teleorman,2020-05-18,43.983333,25.333333
36,38,TM,485,4,49,Timiş,2020-05-18,45.749444,21.227222
37,39,TL,110,0,1,Tulcea,2020-05-18,45.166667,28.800000
38,40,VS,154,0,17,Vaslui,2020-05-18,46.633333,27.733333
39,41,VN,510,0,31,Vrancea,2020-05-18,45.700000,27.183333
40,42,VL,31,0,2,Vâlcea,2020-05-18,45.100000,24.366667